name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  Lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Begin linting
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      
      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint
  CypressTest:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout GitCode
       uses: actions/checkout@v2
 
     - name: Install dependencies
       run: npm install
 
     - name: Start
       run: npm start
 
     - name: Run Cypress Test
       uses: cypress-io/github-action@v4
       with:
         command: npx cypress run
         browser: chrome
